Task_1_5_1
blanedefyne/OOP pull request #12
Opened 2023-12-12 01:06 UTC by blanedefyne

2023-12-12 09:41 UTC, shadrina requested changes

2023-12-12 09:41 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/zelenin/calculator/Atom.java
> +public class Atom {
В данном случае это не более чем обертка String, много удобства она не добавляет. Я имела в виду добавить этой обертке логику по анализу содержимого строки -- чтобы Atom мог понимать, кто он, -- оператор или значение.

2023-12-12 09:41 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/zelenin/calculator/Calculator.java
> +            case "*" -> {
Я не имею ничего против switch по строкам, но хотелось бы воспользоваться знанием о формате этой строки -- мы знаем, что это либо операция из фиксированного множества операций, либо число

2023-12-12 09:41 UTC, shadrina commented on Task_1_5_1/src/test/java/ru/nsu/zelenin/calculator/CalculatorTest.java
> +    public void tooManyArguments() {
Нет операций с нецелочисленными значениями и большого теста, где использовались бы все операции

2023-12-12 11:01 UTC, blanedefyne commented on Task_1_5_1/src/main/java/ru/nsu/zelenin/calculator/Atom.java
> +public class Atom {
я просто как раз не понял, зачем его нужно было делать в таком случае 😅

2023-12-12 14:01 UTC, blanedefyne commented
надеюсь в этот раз понял 
создал 2х наследников класса Atom - Number и Operation
используя instanceof выясняю какой именно атом передо мной - если число, то добавляю в стек; если операция, то вызываю метод, принимающий объект класса Operation
парсер в Atom теперь смотрит на соответствие строк операциям (фиксированному мн-ву), и в default-e выбрасывает InvalidInputException

2023-12-18 10:26 UTC, shadrina approved these changes
Можно лучше, но для сдачи достаточно

2023-12-18 10:26 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/zelenin/calculator/Operation.java
> +    private final String operation;
Положи сюда enum, операций фиксированное количество

2023-12-19 00:35 UTC, merged