Task_2_1_1
blanedefyne/OOP pull request #14
Opened 2024-02-21 12:11 UTC by blanedefyne

2024-02-21 13:30 UTC, blanedefyne commented
![chart (4)](https://github.com/blanedefyne/OOP/assets/89858956/56b3c8ca-0ba5-4fc0-9655-f71a7dbf2321)
В большом тесте создал массив на 25 миллионов простых чисел
Чтобы каждое из решений доходило до конца, и нагляднее была видна разница в скорости (бОльшую часть времени ведь поток "возится" именно с определением - составное число или нет, а не стоит в очереди на инкремент)
Прикладываю указанное на графике время в миллисекундах:
_Progressively_ - **159764**
_Concurrent 2_ - **81470**
_Concurrent 3_ - **57896**
_Concurrent 4_ - **46523**
_Concurrent 5_ - **50154**
_Concurrent 6_ - **50493**
_Concurrent 7_ - **49980**
_Concurrent 8_ - **49919**
_ParallelStream()_ - **49687**

2024-02-21 19:04 UTC, shadrina requested changes

2024-02-21 19:04 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/zelenin/composites/ConcurrentComposites.java
> +    private static boolean answer;
Лучше убрать все статики из этого класса. На почитать: https://stackoverflow.com/questions/3340032/are-utility-classes-evil

У тебя здесь они явно лишние. И вот это просто обычное не-статик состояние.

2024-02-21 19:04 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/zelenin/composites/ConcurrentComposites.java
> +                        synchronized (ConcurrentComposites.class) {
Почитай про volatile в документации. Запись и чтение уже защищены.

2024-02-21 19:04 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/zelenin/composites/ConcurrentComposites.java
> +                    }
У тебя answer же общий, он защищен volatile => его результат будет актуален для любого чтения => тебе необязательно всех прерывать (тем более ты никак не проверяешь, прервано ли исполнение потока). Тебе достаточно просто answer проверять, и если true - выходить.

2024-02-21 19:04 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/zelenin/composites/ConcurrentComposites.java
> +    }
Мы же договорились, что ты перепишешь?

2024-02-22 19:03 UTC, blanedefyne commented on Task_2_1_1/src/main/java/ru/nsu/zelenin/composites/ConcurrentComposites.java
> +                        synchronized (ConcurrentComposites.class) {
Если честно, не сильно понял. Volatile ведь у меня был только для idx, который я потом увеличивал с помощью getNextIndex(). Там обычный инкремент (синхронизованный), а volatile нужен, чтобы изменения в переменной были видны другим потокам.

2024-02-22 19:08 UTC, blanedefyne commented on Task_2_1_1/src/main/java/ru/nsu/zelenin/composites/ConcurrentComposites.java
> +    }
Подумал, что раз время выполнения вроде как адекватное, то видимо решение имеет место быть.
Перепишу

2024-02-26 11:43 UTC, blanedefyne commented
Переписал решение - теперь массив делится на n частей, и каждый поток работает со своей частью

2024-02-26 11:45 UTC, blanedefyne commented
![chart (5)](https://github.com/blanedefyne/OOP/assets/89858956/f2e0c1bc-c111-408b-be59-28b66ba4e6af)
График времени с тестом - 25 миллионов простых чисел. Почти не отличается от прошлого. Ибо тут все равно приходится проверить каждое число

2024-02-26 12:04 UTC, blanedefyne commented
![chart (6)](https://github.com/blanedefyne/OOP/assets/89858956/63636906-9343-43ed-a4a2-4a92a43d2943)
Это уже график с другим тестом - 24999999 простых и одно составное - 80. Место выбрал случайно - 17800000-ый индекс. Чуть дальше 2/3 от всего массива. И тут уже ситуация другая - как раз из-за того, что число находится в начале последней трети - 3 и 6 потоков работают быстрее всего (видимо, имелось в виду это, я в тот раз не сильно понял). Получается, что в среднем разбиение будет работать быстрее и потому, что не простаивает в очереди на инкремент (хотя, к сожалению, то решение на этом тесте я замерить не успел, было бы наверняка нагляднее), и потому, что может возникнуть (и наверное частенько возникает) ситуация, когда число находится относительно недалеко от начала границы какого-то потока - он т.е. доберется до него довольно быстро - как в данном случае с 3 и 6 потоками.
_Progressively_ - **112098**
_Concurrent 2_ - **34693**
_Concurrent 3_ - **8348**
_Concurrent 4_ - **40781**
_Concurrent 5_ - **27054**
_Concurrent 6_ - **12139**
_Concurrent 7_ - **47239**
_Concurrent 8_ - **33312**
_ParallelStream()_ - **49104**

2024-03-07 15:24 UTC, shadrina approved these changes
Ну да, я ответила на комментарий и не опубликовала ревью)

2024-03-07 15:24 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/zelenin/composites/ConcurrentComposites.java
> +                        synchronized (ConcurrentComposites.class) {
А, увидела, что volatile только у индекса. Тогда да, в контексте такого решения надо.

Я, конечно, ожидаю, что ты его перепишешь без лишних синхронизаций.

2024-03-07 16:23 UTC, merged