Task_1_1_1
blanedefyne/OOP pull request #3
Opened 2023-09-12 13:24 UTC by blanedefyne

2023-09-19 18:08 UTC, shadrina requested changes
Посмотри на вкладку "Files changed" на интерфейсе пул реквеста. Есть много лишних файлов, которые к задаче не относятся. Их нужно убрать.

2023-09-19 18:08 UTC, shadrina commented on Task_1_1_1/src/main/java/ru/nsu/zelenin/Heapsort.java
> +public class Heapsort {
Комментарий прилипает к тому, что описывает. Лишний перенос строки.

2023-09-19 18:08 UTC, shadrina commented on Task_1_1_1/src/main/java/ru/nsu/zelenin/Heapsort.java
> +    public static void heapify(int[] arr, int length, int index) {
Тут можно уменьшить область видимости

2023-09-19 18:08 UTC, shadrina commented on Task_1_1_1/src/main/java/ru/nsu/zelenin/Heapsort.java
> +            return new int[0];
А почему бы просто не вернуть arr?

2023-09-19 18:08 UTC, shadrina commented on Task_1_1_1/build.gradle
> +group 'com.example'
Группа автогенерированная, не совпадает с реальностью

2023-09-19 18:08 UTC, shadrina commented on Task_1_1_1/build.gradle
> +  id 'org.beryx.jlink' version '2.25.0'
Тебе точно все это надо?

2023-09-19 18:08 UTC, shadrina commented on Task_1_1_1/build.gradle
> +  mainClass = 'com.example.task_1_1_1.HelloApplication'
Видимо, использовался какой-то шаблон приложения Gradle+Java. Тут надо бы все лишнее почистить.

2023-09-19 18:35 UTC, blanedefyne commented on Task_1_1_1/src/main/java/ru/nsu/zelenin/Heapsort.java
> +            return new int[0];
😅

2023-09-19 18:55 UTC, blanedefyne commented
> Посмотри на вкладку "Files changed" на интерфейсе пул реквеста. Есть много лишних файлов, которые к задаче не относятся. Их нужно убрать.

2023-09-19 18:55 UTC, blanedefyne commented
ай ой

2023-09-26 08:56 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/zelenin/HeapsortTest.java
> +        Assertions.assertArrayEquals(myArray, Heapsort.heapSort(mySecondArray));
Жду исправлений здесь. Сравнивается один и тот же массив сам с собой.

2023-10-03 03:18 UTC, shadrina approved these changes

2023-10-03 04:45 UTC, merged