Task_1_1_2
blanedefyne/OOP pull request #4
Opened 2023-10-01 19:30 UTC by blanedefyne

2023-10-03 08:47 UTC, blanedefyne commented
Class object - грубо говоря главный в java класс (на иерархической вершине)
От него наследуются все другие классы - прямым или косвенным образом (косвенным - если наследуется уже наследник)
Все классы в java могут использовать методы класса Object - toString(), getClass(), hashCode(), equals() и другие.
Обычно их переопределяют
equals() и hashCode() как раз переопределяют вместе, т.к. одинаковые объекты должны возвращать одинаковых хэш
Также, могут возникнуть проблемы с, например, hashMap - не сумеем найти элемент в таблице по ключу
Ну и в целом, если hashCode() вернул false - нет смысл проверять равенство еще и equals, т.к. неизвестно сколько у класса полей, т.е. может быть неэффективно
Вроде все, private поле поправил

2023-10-08 16:45 UTC, shadrina requested changes
Поправь еще варнинги от ревьюдог

2023-10-08 16:45 UTC, shadrina commented on Task_1_1_1/script.sh
> +java -cp build ru.nsu.zelenin.Heapsort
Почему PR добавляет заново первую задачу?

2023-10-08 16:45 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/zelenin/Polynomial.class
Мы не коммитим class файлы в репозиторий

2023-10-08 16:45 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/zelenin/Polynomial.java
> +        return (new Polynomial(res));
Нет нужды во внешних скобках

2023-10-08 16:45 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/zelenin/Polynomial.java
> +        return (new Polynomial(res));
Здесь и далее

2023-10-08 16:45 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/zelenin/Polynomial.java
> +    public String toString() {
Если метод не вмещается в один "экран", лучше разбивать на несколько методов

2023-10-08 16:45 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/zelenin/Polynomial.java
> +    public String toString() {
Для повышения читаемости

2023-10-08 16:45 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/zelenin/Polynomial.java
> +        }
А если какой-то коэффициент посередине равен 0? Например, `3x^3 + x + 1`

2023-10-08 18:09 UTC, blanedefyne commented on Task_1_1_2/src/main/java/ru/nsu/zelenin/Polynomial.class
gitignore не тот был

2023-10-08 18:13 UTC, blanedefyne commented on Task_1_1_2/src/main/java/ru/nsu/zelenin/Polynomial.java
> +        }
он не накапливает значение, просто присваивает i + 1
а по условию старший коэффициент 0 равен не может быть, т.е. мы обязательно наткнемся на ненулевой элемент по пути, а после него могут идти сколько угодно незначащих нулей

2023-10-08 18:18 UTC, blanedefyne commented on Task_1_1_1/script.sh
> +java -cp build ru.nsu.zelenin.Heapsort
что-то намудрил (видимо создал ветку, находясь в ветке task-1-1-1)
лучше удалить ветку ?
чтоб переделать нормально

2023-10-08 20:05 UTC, blanedefyne commented
Вроде все поправил

2023-10-10 04:15 UTC, shadrina reviewed
Варнинги!

2023-10-10 04:15 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/zelenin/Polynomial.java
> +        }
Ок

2023-10-10 04:29 UTC, shadrina approved these changes

2023-10-10 04:30 UTC, merged